# Build a docker container and publish it to Dockerhub.

name: Build x-ui-multilingual

on:
  push:
    branches: [ "develop" ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  IMAGE: x-ui-multilingual
  VERSION: temp

jobs:
  docker_image:
    name: Build x-ui-multilingual Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker configuration
        run: |-
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin

      # Build the Docker image
      - name: Build
        run: |-
          cd x-ui-multilingual
          docker build \
            --target release_candidate \
            --tag "$DOCKER_USER/$IMAGE:$VERSION" \
            --tag "$DOCKER_USER/$IMAGE:latest" \
            --tag "$DOCKER_USER/$IMAGE:focal" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            -f Dockerfile \
            .
      # Push the Docker image to Google Artifact Registry
      - name: Publish
        run: |-
          docker push "$DOCKER_USER/$IMAGE:$VERSION"
          docker push "$DOCKER_USER/$IMAGE:latest"
          docker push "$DOCKER_USER/$IMAGE:focal"
